### ISSUE TITLE
ImportError: cannot import name relativedelta

### ISSUE THREAD

**Issue by vsrathore** [anfederico/Clairvoyant#5]
When i run sample code, following error occured:

**ImportError: cannot import name relativedelta**
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-f95e21b91d55> in <module>()
----> 1 from clairvoyant import Backtest

.\venv\Lib\site-packages\clairvoyant\__init__.py in <module>()
----> 1 from Backtest import Backtest

.\venv\Lib\site-packages\clairvoyant\Backtest.py in <module>()
     10 from numpy                 import vstack, hstack
     11 from csv                   import DictWriter
---> 12 from pandas.tslib          import relativedelta
     13 from dateutil.parser       import parse

_________________________
My Pandas version : 0.14.1

**Comment by anfederico** [comment]
I'm not sure what the problem is, do you have pandas installed?

**Comment by vsrathore** [comment]
Yes, i do have Pandas version : 0.14.1 installed.
And the problem is: ImportError
ImportError: cannot import name relativedelta

May be : relativedelta module is not part of pandas.tslib

**Comment by anfederico** [comment]
Reinstall pandas, you should have >= 0.18.1 installed. That might help.

**Comment by vsrathore** [comment]
Yeah.. Problem solved after updating pandas version to 0.18.1
I think you need to define requirements.txt for further ease.
